openapi: 3.0.0
info:
  title: Todo API
  description: Endpoints for managing todos and todo lists
responses:
  OkResponse:
    description: Successful response
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/models.response.MessageResponse'
  BadRequest:
    description: Malformed request
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/models.response.ErrorResponse'
  NotFound:
    description: Resource not found
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/models.response.ErrorResponse'
  InternalServerError:
    description: Server error occurred
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/models.response.ErrorResponse'
